setup.py: fixed missing of wheel
error: invalid command 'bdist_wheel'
ERROR: Failed building wheel for mdutils

Credits to: https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>